In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
college = pd.read_csv('master/data/college.csv')
columns = college.columns
columns

Index(['INSTNM', 'CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL',
       'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS', 'UGDS_WHITE',
       'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI',
       'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'CURROPER', 'PCTPELL',
       'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP'],
      dtype='object')

In [3]:
columns.values

array(['INSTNM', 'CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY',
       'RELAFFIL', 'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS',
       'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN',
       'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF',
       'CURROPER', 'PCTPELL', 'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10',
       'GRAD_DEBT_MDN_SUPP'], dtype=object)

In [4]:
columns[5]

'WOMENONLY'

In [5]:
columns[[1, 8, 10]]

Index(['CITY', 'SATMTMID', 'UGDS'], dtype='object')

In [6]:
columns[-7:-4]

Index(['PPTUG_EF', 'CURROPER', 'PCTPELL'], dtype='object')

In [7]:
columns.min(), columns.max(), columns.isnull().sum()

('CITY', 'WOMENONLY', 0)

In [8]:
columns + 'A'

Index(['INSTNMA', 'CITYA', 'STABBRA', 'HBCUA', 'MENONLYA', 'WOMENONLYA',
       'RELAFFILA', 'SATVRMIDA', 'SATMTMIDA', 'DISTANCEONLYA', 'UGDSA',
       'UGDS_WHITEA', 'UGDS_BLACKA', 'UGDS_HISPA', 'UGDS_ASIANA', 'UGDS_AIANA',
       'UGDS_NHPIA', 'UGDS_2MORA', 'UGDS_NRAA', 'UGDS_UNKNA', 'PPTUG_EFA',
       'CURROPERA', 'PCTPELLA', 'PCTFLOANA', 'UG25ABVA', 'MD_EARN_WNE_P10A',
       'GRAD_DEBT_MDN_SUPPA'],
      dtype='object')

In [9]:
columns > 'G'

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True])

In [10]:
# columns[1] = 'city'
# TypeError: Index does not support mutable operations

In [11]:
c1 = columns[:4]
c1

Index(['INSTNM', 'CITY', 'STABBR', 'HBCU'], dtype='object')

In [12]:
c2 = columns[2:6]
c2

Index(['STABBR', 'HBCU', 'MENONLY', 'WOMENONLY'], dtype='object')

In [13]:
c1.union(c2) # or c1 | c2

Index(['CITY', 'HBCU', 'INSTNM', 'MENONLY', 'STABBR', 'WOMENONLY'], dtype='object')

In [14]:
c1.intersection(c2) # c1 & c2

Index(['STABBR', 'HBCU'], dtype='object')

In [15]:
c1.symmetric_difference(c2) # or c1 ^ c2

Index(['CITY', 'INSTNM', 'MENONLY', 'WOMENONLY'], dtype='object')

## Producing Cartesian products

In [16]:
s1 = pd.Series(index=list('aaab'), data=np.arange(4))
s1

a    0
a    1
a    2
b    3
dtype: int32

In [17]:
s2 = pd.Series(index=list('cababb'), data=np.arange(6))
s2

c    0
a    1
b    2
a    3
b    4
b    5
dtype: int32

In [18]:
s1 + s2

a    1.0
a    3.0
a    2.0
a    4.0
a    3.0
a    5.0
b    5.0
b    7.0
b    8.0
c    NaN
dtype: float64

In [19]:
s1 = pd.Series(index=list('aaabb'), data=np.arange(5))
s1

a    0
a    1
a    2
b    3
b    4
dtype: int32

In [20]:
s2 = pd.Series(index=list('aaabb'), data=np.arange(5))
s1 + s2

a    0
a    2
a    4
b    6
b    8
dtype: int32

In [21]:
s1 = pd.Series(index=list('aaabb'), data=np.arange(5))
s2 = pd.Series(index=list('bbaaa'), data=np.arange(5))
s1 + s2

a    2
a    3
a    4
a    3
a    4
a    5
a    4
a    5
a    6
b    3
b    4
b    4
b    5
dtype: int32

## Exploding indexes

In [22]:
employee = pd.read_csv('master/data/employee.csv', index_col='RACE')
employee.head()

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
RACE,,,,,,,,,
Hispanic/Latino,0,ASSISTANT DIRECTOR (EX LVL),Municipal Courts Department,121862.0,Full Time,Female,Active,2006-06-12,2012-10-13
Hispanic/Latino,1,LIBRARY ASSISTANT,Library,26125.0,Full Time,Female,Active,2000-07-19,2010-09-18
White,2,POLICE OFFICER,Houston Police Department-HPD,45279.0,Full Time,Male,Active,2015-02-03,2015-02-03
White,3,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,Full Time,Male,Active,1982-02-08,1991-05-25
White,4,ELECTRICIAN,General Services Department,56347.0,Full Time,Male,Active,1989-06-19,1994-10-22

In [23]:
salary1 = employee['BASE_SALARY']
salary2 = employee['BASE_SALARY']
salary1 is salary2

True

In [24]:
salary1 = employee['BASE_SALARY'].copy()
salary2 = employee['BASE_SALARY'].copy()
salary1 is salary2

False

In [25]:
salary1 = salary1.sort_index()
salary1.head()

RACE
American Indian or Alaskan Native    78355.0
American Indian or Alaskan Native    26125.0
American Indian or Alaskan Native    98536.0
American Indian or Alaskan Native        NaN
American Indian or Alaskan Native    55461.0
Name: BASE_SALARY, dtype: float64

In [26]:
salary2.head()

RACE
Hispanic/Latino    121862.0
Hispanic/Latino     26125.0
White               45279.0
White               63166.0
White               56347.0
Name: BASE_SALARY, dtype: float64

In [27]:
salary_add = salary1 + salary2
salary_add.head()

RACE
American Indian or Alaskan Native    138702.0
American Indian or Alaskan Native    156710.0
American Indian or Alaskan Native    176891.0
American Indian or Alaskan Native    159594.0
American Indian or Alaskan Native    127734.0
Name: BASE_SALARY, dtype: float64

In [28]:
salary_add1 = salary1 + salary1
len(salary1), len(salary2), len(salary_add), len(salary_add1)

(2000, 2000, 1175424, 2000)

In [29]:
index_vc = salary1.index.value_counts(dropna=False)
index_vc

Black or African American            700
White                                665
Hispanic/Latino                      480
Asian/Pacific Islander               107
NaN                                   35
American Indian or Alaskan Native     11
Others                                 2
Name: RACE, dtype: int64

In [30]:
index_vc.pow(2).sum()

1175424

## Filling values with unequal indexes

In [31]:
baseball_14 = pd.read_csv('master/data/baseball14.csv',
                          index_col='playerID')
baseball_15 = pd.read_csv('master/data/baseball15.csv',
                          index_col='playerID')
baseball_16 = pd.read_csv('master/data/baseball16.csv',
                          index_col='playerID')
baseball_14.head()

,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
playerID,,,,,,,,,,,,,,,,,,,,,
altuvjo01,2014,1,HOU,AL,158,660,85,225,47,3,...,59.0,56.0,9.0,36,53.0,7.0,5.0,1.0,5.0,20.0
cartech02,2014,1,HOU,AL,145,507,68,115,21,1,...,88.0,5.0,2.0,56,182.0,6.0,5.0,0.0,4.0,12.0
castrja01,2014,1,HOU,AL,126,465,43,103,21,2,...,56.0,1.0,0.0,34,151.0,1.0,9.0,1.0,3.0,11.0
corpoca01,2014,1,HOU,AL,55,170,22,40,6,0,...,19.0,0.0,0.0,14,37.0,0.0,3.0,1.0,2.0,3.0
dominma01,2014,1,HOU,AL,157,564,51,121,17,0,...,57.0,0.0,1.0,29,125.0,2.0,5.0,2.0,7.0,23.0

In [32]:
baseball_14.index.difference(baseball_15.index)

Index(['corpoca01', 'dominma01', 'fowlede01', 'grossro01', 'guzmaje01',
       'hoeslj01', 'krausma01', 'preslal01', 'singljo02'],
      dtype='object', name='playerID')

In [33]:
baseball_14.index.difference(baseball_16.index)

Index(['cartech02', 'corpoca01', 'dominma01', 'fowlede01', 'grossro01',
       'guzmaje01', 'hoeslj01', 'krausma01', 'preslal01', 'singljo02',
       'villajo01'],
      dtype='object', name='playerID')

In [34]:
hits_14 = baseball_14['H']
hits_15 = baseball_15['H']
hits_16 = baseball_16['H']
hits_14.head()

playerID
altuvjo01    225
cartech02    115
castrja01    103
corpoca01     40
dominma01    121
Name: H, dtype: int64

In [35]:
(hits_14 + hits_15).head()

playerID
altuvjo01    425.0
cartech02    193.0
castrja01    174.0
congeha01      NaN
corpoca01      NaN
Name: H, dtype: float64

In [36]:
hits_14.add(hits_15, fill_value=0).head()

playerID
altuvjo01    425.0
cartech02    193.0
castrja01    174.0
congeha01     46.0
corpoca01     40.0
Name: H, dtype: float64

In [37]:
hits_total = hits_14.add(hits_15, fill_value=0) \
                    .add(hits_16, fill_value=0)
hits_total.head()

playerID
altuvjo01    641.0
bregmal01     53.0
cartech02    193.0
castrja01    243.0
congeha01     46.0
Name: H, dtype: float64

In [38]:
hits_total.hasnans

False

In [39]:
s = pd.Series(index=['a', 'b', 'c', 'd'],
              data=[np.nan, 3, np.nan, 1])
s

a    NaN
b    3.0
c    NaN
d    1.0
dtype: float64

In [40]:
s1 = pd.Series(index=['a', 'b', 'c'], data=[np.nan, 6, 10])
s1

a     NaN
b     6.0
c    10.0
dtype: float64

In [41]:
s.add(s1, fill_value=5)

a     NaN
b     9.0
c    15.0
d     6.0
dtype: float64

In [42]:
df_14 = baseball_14[['G', 'AB', 'R', 'H']]
df_14.head()

             G   AB   R    H
playerID
altuvjo01  158  660  85  225
cartech02  145  507  68  115
castrja01  126  465  43  103
corpoca01   55  170  22   40
dominma01  157  564  51  121

In [43]:
df_15 = baseball_15[['AB', 'R', 'H', 'HR']]
df_15.head()

            AB   R    H  HR
playerID
altuvjo01  638  86  200  15
cartech02  391  50   78  24
castrja01  337  38   71  11
congeha01  201  25   46  11
correca01  387  52  108  22

In [44]:
(df_14 + df_15).head(10).style.highlight_null('yellow')

In [45]:
df_14.add(df_15, fill_value=0).head(10) \
     .style.highlight_null('yellow')

## Appending columns from different DataFrames

In [46]:
employee = pd.read_csv('master/data/employee.csv')
dept_sal = employee[['DEPARTMENT', 'BASE_SALARY']]
dept_sal.head()

                      DEPARTMENT  BASE_SALARY
0    Municipal Courts Department     121862.0
1                        Library      26125.0
2  Houston Police Department-HPD      45279.0
3  Houston Fire Department (HFD)      63166.0
4    General Services Department      56347.0

In [47]:
dept_sal = dept_sal.sort_values(['DEPARTMENT', 'BASE_SALARY'],
                                  ascending=[True, False])
dept_sal.head()

                      DEPARTMENT  BASE_SALARY
1494  Admn. & Regulatory Affairs     140416.0
237   Admn. & Regulatory Affairs     130416.0
1679  Admn. & Regulatory Affairs     103776.0
988   Admn. & Regulatory Affairs      72741.0
693   Admn. & Regulatory Affairs      66825.0

In [48]:
max_dept_sal = dept_sal.drop_duplicates(subset='DEPARTMENT')
max_dept_sal.head()

                        DEPARTMENT  BASE_SALARY
1494    Admn. & Regulatory Affairs     140416.0
149       City Controller's Office      64251.0
236                   City Council     100000.0
647   Convention and Entertainment      38397.0
1500   Dept of Neighborhoods (DON)      89221.0

In [49]:
max_dept_sal = max_dept_sal.set_index('DEPARTMENT')

In [50]:
max_dept_sal.head()

                              BASE_SALARY
DEPARTMENT
Admn. & Regulatory Affairs       140416.0
City Controller's Office          64251.0
City Council                     100000.0
Convention and Entertainment      38397.0
Dept of Neighborhoods (DON)       89221.0

In [51]:
employee = employee.set_index('DEPARTMENT')

In [52]:
employee.head()

,UNIQUE_ID,POSITION_TITLE,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
DEPARTMENT,,,,,,,,,
Municipal Courts Department,0,ASSISTANT DIRECTOR (EX LVL),121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13
Library,1,LIBRARY ASSISTANT,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18
Houston Police Department-HPD,2,POLICE OFFICER,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03
Houston Fire Department (HFD),3,ENGINEER/OPERATOR,63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25
General Services Department,4,ELECTRICIAN,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22

In [53]:
employee['MAX_DEPT_SALARY'] = max_dept_sal['BASE_SALARY']
employee.head()

,UNIQUE_ID,POSITION_TITLE,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE,MAX_DEPT_SALARY
DEPARTMENT,,,,,,,,,,
Municipal Courts Department,0,ASSISTANT DIRECTOR (EX LVL),121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13,121862.0
Library,1,LIBRARY ASSISTANT,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18,107763.0
Houston Police Department-HPD,2,POLICE OFFICER,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03,199596.0
Houston Fire Department (HFD),3,ENGINEER/OPERATOR,63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25,210588.0
General Services Department,4,ELECTRICIAN,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22,89194.0

In [54]:
employee.query('BASE_SALARY > MAX_DEPT_SALARY')

Empty DataFrame
Columns: [UNIQUE_ID, POSITION_TITLE, BASE_SALARY, RACE, EMPLOYMENT_TYPE, GENDER, EMPLOYMENT_STATUS, HIRE_DATE, JOB_DATE, MAX_DEPT_SALARY]
Index: []

In [55]:
np.random.seed(1234)
random_salary = dept_sal.sample(n=10).set_index('DEPARTMENT')
random_salary

                                BASE_SALARY
DEPARTMENT
Public Works & Engineering-PWE      50586.0
Houston Police Department-HPD       66614.0
Houston Police Department-HPD       66614.0
Housing and Community Devp.         78853.0
Houston Police Department-HPD       66614.0
Parks & Recreation                      NaN
Public Works & Engineering-PWE      37211.0
Public Works & Engineering-PWE      54683.0
Human Resources Dept.               58474.0
Health & Human Services             47050.0

In [56]:
# employee['RANDOM_SALARY'] = random_salary['BASE_SALARY']
# ValueError: cannot reindex from a duplicate axis

In [57]:
employee['MAX_SALARY2'] = max_dept_sal['BASE_SALARY'].head(3)

In [58]:
employee.MAX_SALARY2.value_counts()

140416.0    29
100000.0    11
64251.0      5
Name: MAX_SALARY2, dtype: int64

In [59]:
employee.MAX_SALARY2.isnull().mean()

0.9775

## Highlighting the maximum value from each column

In [60]:
college = pd.read_csv('master/data/college.csv', index_col='INSTNM')
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [61]:
college.dtypes

CITY                   object
STABBR                 object
HBCU                  float64
MENONLY               float64
WOMENONLY             float64
RELAFFIL                int64
SATVRMID              float64
SATMTMID              float64
DISTANCEONLY          float64
UGDS                  float64
UGDS_WHITE            float64
UGDS_BLACK            float64
UGDS_HISP             float64
UGDS_ASIAN            float64
UGDS_AIAN             float64
UGDS_NHPI             float64
UGDS_2MOR             float64
UGDS_NRA              float64
UGDS_UNKN             float64
PPTUG_EF              float64
CURROPER                int64
PCTPELL               float64
PCTFLOAN              float64
UG25ABV               float64
MD_EARN_WNE_P10        object
GRAD_DEBT_MDN_SUPP     object
dtype: object

In [62]:
college.MD_EARN_WNE_P10.iloc[0]

'30300'

In [63]:
college.GRAD_DEBT_MDN_SUPP.iloc[0]

'33888'

In [64]:
college.MD_EARN_WNE_P10.sort_values(ascending=False).head()

INSTNM
Sharon Regional Health System School of Nursing    PrivacySuppressed
Northcoast Medical Training Academy                PrivacySuppressed
Success Schools                                    PrivacySuppressed
Louisiana Culinary Institute                       PrivacySuppressed
Bais Medrash Toras Chesed                          PrivacySuppressed
Name: MD_EARN_WNE_P10, dtype: object

In [65]:
cols = ['MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP']
for col in cols:
    college[col] = pd.to_numeric(college[col], errors='coerce')

In [66]:
type(college.loc['Sharon Regional Health System School of Nursing', 'MD_EARN_WNE_P10'])

numpy.float64

In [67]:
college.dtypes.loc[cols]

MD_EARN_WNE_P10       float64
GRAD_DEBT_MDN_SUPP    float64
dtype: object

In [68]:
college_n = college.select_dtypes(include=[np.number])
college_n.head()

,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,0.0333,0.9353,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300.0,33888.0
University of Alabama at Birmingham,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,0.5922,0.2600,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700.0,21941.5
Amridge University,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,0.2990,0.4192,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100.0,23370.0
University of Alabama in Huntsville,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,0.6988,0.1255,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500.0,24097.0
Alabama State University,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,0.0158,0.9208,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600.0,33118.5

In [69]:
criteria = college_n.nunique() == 2
criteria.head()

HBCU          True
MENONLY       True
WOMENONLY     True
RELAFFIL      True
SATVRMID     False
dtype: bool

In [70]:
binary_cols = college_n.columns[criteria].tolist()
binary_cols

['HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL', 'DISTANCEONLY', 'CURROPER']

In [71]:
college_n2 = college_n.drop(labels=binary_cols, axis='columns')
college_n2.head()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,424.0,420.0,4206.0,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138,0.0656,0.7356,0.8284,0.1049,30300.0,33888.0
University of Alabama at Birmingham,570.0,565.0,11383.0,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100,0.2607,0.3460,0.5214,0.2422,39700.0,21941.5
Amridge University,NaN,NaN,291.0,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715,0.4536,0.6801,0.7795,0.8540,40100.0,23370.0
University of Alabama in Huntsville,595.0,590.0,5451.0,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350,0.2146,0.3072,0.4596,0.2640,45500.0,24097.0
Alabama State University,425.0,430.0,4811.0,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137,0.0892,0.7347,0.7554,0.1270,26600.0,33118.5

In [72]:
max_cols = college_n2.idxmax()
max_cols

SATVRMID                             California Institute of Technology
SATMTMID                             California Institute of Technology
UGDS                                      University of Phoenix-Arizona
UGDS_WHITE                       Mr Leon's School of Hair Design-Moscow
UGDS_BLACK                           Velvatex College of Beauty Culture
UGDS_HISP                       Thunderbird School of Global Management
UGDS_ASIAN                          Cosmopolitan Beauty and Tech School
UGDS_AIAN                             Haskell Indian Nations University
UGDS_NHPI                                       Palau Community College
UGDS_2MOR                                                 LIU Brentwood
UGDS_NRA               California University of Management and Sciences
UGDS_UNKN             Le Cordon Bleu College of Culinary Arts-San Fr...
PPTUG_EF                        Thunderbird School of Global Management
PCTPELL                                        MTI Business College Inc
PCTFLOAN                                         ABC Beauty College Inc
UG25ABV                                  Dongguk University-Los Angeles
MD_EARN_WNE_P10                            Medical College of Wisconsin
GRAD_DEBT_MDN_SUPP           Southwest University of Visual Arts-Tucson
dtype: object

In [73]:
unique_max_cols = max_cols.unique()
unique_max_cols[:5]

array(['California Institute of Technology',
       'University of Phoenix-Arizona',
       "Mr Leon's School of Hair Design-Moscow",
       'Velvatex College of Beauty Culture',
       'Thunderbird School of Global Management'], dtype=object)

In [74]:
college_n2.loc[unique_max_cols].style.highlight_max()

In [75]:
college = pd.read_csv('master/data/college.csv', index_col='INSTNM')
college_ugds = college.filter(like='UGDS_').head()
college_ugds.style.highlight_max(axis='columns')

## Replicating idxmax with method chaining

In [76]:
college = pd.read_csv('master/data/college.csv', index_col='INSTNM')
cols = ['MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP']

In [77]:
college[cols].head()

                                    MD_EARN_WNE_P10 GRAD_DEBT_MDN_SUPP
INSTNM
Alabama A & M University                      30300              33888
University of Alabama at Birmingham           39700            21941.5
Amridge University                            40100              23370
University of Alabama in Huntsville           45500              24097
Alabama State University                      26600            33118.5

In [78]:
college['MD_EARN_WNE_P10'].dropna().sort_values().tail()

INSTNM
Bais Medrash Toras Chesed                          PrivacySuppressed
Louisiana Culinary Institute                       PrivacySuppressed
Success Schools                                    PrivacySuppressed
Northcoast Medical Training Academy                PrivacySuppressed
Sharon Regional Health System School of Nursing    PrivacySuppressed
Name: MD_EARN_WNE_P10, dtype: object

In [79]:
for col in cols:
    college[col] = pd.to_numeric(college[col], errors='coerce')

In [80]:
# Disgretion: on constate que la variable col a été créée lors de la precédente boucle for et que
# retiens la dernière valeur qui lui a été affectée

col

'GRAD_DEBT_MDN_SUPP'

In [81]:
college_n = college.select_dtypes(include=[np.number])
college_n

,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,0.0333,0.9353,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300.0,33888.0
University of Alabama at Birmingham,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,0.5922,0.2600,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700.0,21941.5
Amridge University,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,0.2990,0.4192,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100.0,23370.0
University of Alabama in Huntsville,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,0.6988,0.1255,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500.0,24097.0
Alabama State University,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,0.0158,0.9208,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600.0,33118.5
The University of Alabama,0.0,0.0,0.0,0,555.0,565.0,0.0,29851.0,0.7825,0.1119,...,0.0261,0.0268,0.0026,0.0844,1,0.2040,0.4010,0.0853,41900.0,23750.0
Central Alabama Community College,0.0,0.0,0.0,0,NaN,NaN,0.0,1592.0,0.7255,0.2613,...,0.0000,0.0000,0.0019,0.3882,1,0.5892,0.3977,0.3153,27500.0,16127.0
Athens State University,0.0,0.0,0.0,0,NaN,NaN,0.0,2991.0,0.7823,0.1200,...,0.0174,0.0057,0.0334,0.5517,1,0.4088,0.6296,0.6410,39000.0,18595.0
Auburn University at Montgomery,0.0,0.0,0.0,0,486.0,509.0,0.0,4304.0,0.5328,0.3376,...,0.0297,0.0397,0.0246,0.2853,1,0.4192,0.5803,0.2930,35000.0,21335.0
Auburn University,0.0,0.0,0.0,0,575.0,588.0,0.0,20514.0,0.8507,0.0704,...,0.0000,0.0100,0.0140,0.0862,1,0.1610,0.3494,0.0415,45700.0,21831.0
Birmingham Southern College,0.0,0.0,0.0,1,560.0,560.0,0.0,1180.0,0.7983,0.1102,...,0.0051,0.0000,0.0051,0.0017,1,0.1920,0.4809,0.0152,44200.0,27000.0
Chattahoochee Valley Community College,0.0,0.0,0.0,0,NaN,NaN,0.0,1727.0,0.4661,0.4372,...,0.0151,0.0000,0.0139,0.4198,1,0.6369,0.2537,0.3876,26100.0,9000.0
Concordia College Alabama,1.0,0.0,0.0,1,420.0,400.0,0.0,322.0,0.0280,0.8758,...,0.0031,0.0466,0.0000,0.1056,1,0.8667,0.9333,0.2367,19900.0,NaN
South University-Montgomery,0.0,0.0,0.0,0,NaN,NaN,0.0,522.0,0.3046,0.6054,...,0.0000,0.0019,0.0326,0.3238,1,0.6845,0.7129,0.5726,28800.0,25167.0
Enterprise State Community College,0.0,0.0,0.0,0,NaN,NaN,0.0,1729.0,0.6408,0.2435,...,0.0254,0.0012,0.0069,0.3823,1,0.4895,0.2263,0.3399,24600.0,8273.0
James H Faulkner State Community College,0.0,0.0,0.0,0,NaN,NaN,0.0,4286.0,0.6979,0.2259,...,0.0152,0.0007,0.0009,0.4104,1,0.4725,0.3741,0.2909,28700.0,11000.0
Faulkner University,0.0,0.0,0.0,1,NaN,NaN,0.0,2367.0,0.3874,0.5137,...,0.0173,0.0182,0.0258,0.2302,1,0.5812,0.7253,0.4589,37200.0,22000.0
Gadsden State Community College,1.0,0.0,0.0,0,NaN,NaN,0.0,4917.0,0.6921,0.2076,...,0.0185,0.0150,0.0169,0.4523,1,0.5734,0.0000,0.3733,25700.0,NaN
New Beginning College of Cosmetology,0.0,0.0,0.0,0,NaN,NaN,0.0,115.0,0.8957,0.0348,...,0.0000,0.0000,0.0000,0.0783,1,0.8224,0.8553,0.3933,NaN,5500.0
George C Wallace State Community College-Dothan,0.0,0.0,0.0,0,NaN,NaN,0.0,4293.0,0.6273,0.3240,...,0.0126,0.0000,0.0009,0.4787,1,0.5501,0.0000,0.3920,26600.0,NaN
George C Wallace State Community College-Hanceville,0.0,0.0,0.0,0,NaN,NaN,0.0,4920.0,0.8630,0.0612,...,0.0000,0.0059,0.0183,0.4203,1,0.5026,0.4192,0.3229,28800.0,11186.0
George C Wallace State Community College-Selma,0.0,0.0,0.0,0,NaN,NaN,0.0,1513.0,0.1956,0.7449,...,0.0033,0.0040,0.0443,0.3840,1,0.7645,0.0000,0.3318,24200.0,NaN
Herzing University-Birmingham,0.0,0.0,0.0,0,NaN,NaN,0.0,302.0,0.3543,0.5265,...,0.0563,0.0000,0.0397,0.5497,1,0.6541,0.7736,0.7813,42300.0,23216.5
Huntingdon College,0.0,0.0,0.0,1,510.0,490.0,0.0,1149.0,0.6388,0.1993,...,0.0261,0.0061,0.0827,0.2097,1,0.3982,0.7153,0.1937,36500.0,26230.0
Heritage Christian University,0.0,0.0,0.0,1,NaN,NaN,0.0,62.0,0.7419,0.1129,...,0.0000,0.0161,0.0323,0.4355,1,0.6087,0.4493,0.5942,NaN,NaN
J F Drake State Community and Technical College,1.0,0.0,0.0,0,NaN,NaN,0.0,974.0,0.3337,0.5965,...,0.0185,0.0000,0.0062,0.4394,1,0.5763,0.0000,0.4555,22300.0,NaN
Jacksonville State University,0.0,0.0,0.0,0,495.0,485.0,0.0,7060.0,0.6834,0.2382,...,0.0000,0.0234,0.0280,0.1989,1,0.4428,0.6825,0.2200,34600.0,23000.0
Jefferson Davis Community College,0.0,0.0,0.0,0,NaN,NaN,0.0,1033.0,0.5857,0.2982,...,0.0184,0.0000,0.0397,0.4424,1,0.5765,0.0000,0.4060,25400.0,NaN
Jefferson State Community College,0.0,0.0,0.0,0,NaN,NaN,0.0,7443.0,0.6696,0.2246,...,0.0301,0.0054,0.0001,0.6050,1,0.3372,0.2101,0.3671,29400.0,8916.5
John C Calhoun State Community College,0.0,0.0,0.0,0,NaN,NaN,0.0,9380.0,0.6528,0.1940,...,0.0428,0.0062,0.0162,0.5795,1,0.3933,0.3024,0.3688,27400.0,10500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Piscataway,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Utah County Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,7667.0
L'esprit Academy - Royal Oak,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9833.0
National Career Institute - Jersey City Branch,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9500.0
Strayer University-Cobb Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Morrow Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Roswell Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Douglasville Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Lithonia Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Savannah Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Augusta Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Columbus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Columbia Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Charleston Campus,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Irving,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Katy,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Northwest Houston,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Plano,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200.0,36173.5
Strayer University-Cedar Hill,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
Strayer University-North Dallas,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
Strayer University-San Antonio,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
Strayer University-Stafford,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
WestMed College - Merced,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,15623.5
Vantage College,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9500.0
SAE Institute of Technology San Francisco,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9500.0
Rasmussen College - Overland Park,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,21163.0
National Personal Training Institute of Cleveland,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,6333.0
Bay Area Medical Academy - San Jose Satellite Location,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
Excel Learning Center-San Antonio South,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,12125.0

In [82]:
college_n.nunique()

HBCU                     2
MENONLY                  2
WOMENONLY                2
RELAFFIL                 2
SATVRMID               163
SATMTMID               167
DISTANCEONLY             2
UGDS                  2932
UGDS_WHITE            4397
UGDS_BLACK            3242
UGDS_HISP             2809
UGDS_ASIAN            1254
UGDS_AIAN              601
UGDS_NHPI              363
UGDS_2MOR              957
UGDS_NRA               920
UGDS_UNKN             1517
PPTUG_EF              3420
CURROPER                 2
PCTPELL               4422
PCTFLOAN              4155
UG25ABV               4285
MD_EARN_WNE_P10        597
GRAD_DEBT_MDN_SUPP    2037
dtype: int64

In [83]:
college_n.nunique() == 2

HBCU                   True
MENONLY                True
WOMENONLY              True
RELAFFIL               True
SATVRMID              False
SATMTMID              False
DISTANCEONLY           True
UGDS                  False
UGDS_WHITE            False
UGDS_BLACK            False
UGDS_HISP             False
UGDS_ASIAN            False
UGDS_AIAN             False
UGDS_NHPI             False
UGDS_2MOR             False
UGDS_NRA              False
UGDS_UNKN             False
PPTUG_EF              False
CURROPER               True
PCTPELL               False
PCTFLOAN              False
UG25ABV               False
MD_EARN_WNE_P10       False
GRAD_DEBT_MDN_SUPP    False
dtype: bool

In [84]:
criteria = college_n.nunique() == 2

In [85]:
college_n.columns[criteria]

Index(['HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL', 'DISTANCEONLY', 'CURROPER'], dtype='object')

In [86]:
binary_cols = college_n.columns[criteria].tolist()

In [87]:
binary_cols

['HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL', 'DISTANCEONLY', 'CURROPER']

In [88]:
college_n = college_n.drop(labels=binary_cols, axis='columns')

In [89]:
college_n.max().head()

SATVRMID         765.0
SATMTMID         785.0
UGDS          151558.0
UGDS_WHITE         1.0
UGDS_BLACK         1.0
dtype: float64

In [90]:
college_n.eq(college_n.max()).head()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Alabama at Birmingham,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Amridge University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Alabama in Huntsville,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Alabama State University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [91]:
has_row_max = college_n.eq(college_n.max()).any(axis='columns')
has_row_max.head()

INSTNM
Alabama A & M University               False
University of Alabama at Birmingham    False
Amridge University                     False
University of Alabama in Huntsville    False
Alabama State University               False
dtype: bool

In [92]:
college_n.shape

(7535, 18)

In [93]:
has_row_max.sum()

401

In [94]:
college_n.eq(college_n.max()).cumsum()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama at Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Amridge University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama in Huntsville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alabama State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
The University of Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Central Alabama Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Athens State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University at Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Birmingham Southern College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Chattahoochee Valley Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Concordia College Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
South University-Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Enterprise State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
James H Faulkner State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Faulkner University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gadsden State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
New Beginning College of Cosmetology,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Dothan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Hanceville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Selma,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Herzing University-Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Huntingdon College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Heritage Christian University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J F Drake State Community and Technical College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jacksonville State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson Davis Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
John C Calhoun State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Piscataway,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Utah County Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
L'esprit Academy - Royal Oak,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
National Career Institute - Jersey City Branch,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Cobb Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Morrow Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Roswell Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Douglasville Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Lithonia Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Savannah Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Augusta Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Columbus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Columbia Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Charleston Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Irving,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Katy,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Northwest Houston,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Plano,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Cedar Hill,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-North Dallas,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-San Antonio,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Stafford,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
WestMed College - Merced,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Vantage College,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
SAE Institute of Technology San Francisco,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Rasmussen College - Overland Park,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
National Personal Training Institute of Cleveland,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Bay Area Medical Academy - San Jose Satellite Location,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Excel Learning Center-San Antonio South,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2

In [95]:
college_n.eq(college_n.max()).cumsum().cumsum()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama at Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Amridge University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama in Huntsville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alabama State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
The University of Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Central Alabama Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Athens State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University at Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Birmingham Southern College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Chattahoochee Valley Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Concordia College Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
South University-Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Enterprise State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
James H Faulkner State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Faulkner University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gadsden State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
New Beginning College of Cosmetology,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Dothan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Hanceville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Selma,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Herzing University-Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Huntingdon College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Heritage Christian University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J F Drake State Community and Technical College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jacksonville State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson Davis Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
John C Calhoun State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,7280,7280,390,377025,72407,337703,958,11332,3291,5031,1051,7251,112549,171294,168898,35883,3420,10216
Strayer University-Piscataway,7281,7281,391,377134,72435,337839,959,11334,3292,5032,1052,7252,112593,171360,168953,35895,3421,10218
Utah County Campus,7282,7282,392,377243,72463,337975,960,11336,3293,5033,1053,7253,112637,171426,169008,35907,3422,10220
L'esprit Academy - Royal Oak,7283,7283,393,377352,72491,338111,961,11338,3294,5034,1054,7254,112681,171492,169063,35919,3423,10222
National Career Institute - Jersey City Branch,7284,7284,394,377461,72519,338247,962,11340,3295,5035,1055,7255,112725,171558,169118,35931,3424,10224
Strayer University-Cobb Campus,7285,7285,395,377570,72547,338383,963,11342,3296,5036,1056,7256,112769,171624,169173,35943,3425,10226
Strayer University-Morrow Campus,7286,7286,396,377679,72575,338519,964,11344,3297,5037,1057,7257,112813,171690,169228,35955,3426,10228
Strayer University-Roswell Campus,7287,7287,397,377788,72603,338655,965,11346,3298,5038,1058,7258,112857,171756,169283,35967,3427,10230
Strayer University-Douglasville Campus,7288,7288,398,377897,72631,338791,966,11348,3299,5039,1059,7259,112901,171822,169338,35979,3428,10232
Strayer University-Lithonia Campus,7289,7289,399,378006,72659,338927,967,11350,3300,5040,1060,7260,112945,171888,169393,35991,3429,10234
Strayer University-Savannah Campus,7290,7290,400,378115,72687,339063,968,11352,3301,5041,1061,7261,112989,171954,169448,36003,3430,10236
Strayer University-Augusta Campus,7291,7291,401,378224,72715,339199,969,11354,3302,5042,1062,7262,113033,172020,169503,36015,3431,10238
Strayer University-Columbus,7292,7292,402,378333,72743,339335,970,11356,3303,5043,1063,7263,113077,172086,169558,36027,3432,10240
Strayer University-Columbia Campus,7293,7293,403,378442,72771,339471,971,11358,3304,5044,1064,7264,113121,172152,169613,36039,3433,10242
Strayer University-Charleston Campus,7294,7294,404,378551,72799,339607,972,11360,3305,5045,1065,7265,113165,172218,169668,36051,3434,10244
Strayer University-Irving,7295,7295,405,378660,72827,339743,973,11362,3306,5046,1066,7266,113209,172284,169723,36063,3435,10246
Strayer University-Katy,7296,7296,406,378769,72855,339879,974,11364,3307,5047,1067,7267,113253,172350,169778,36075,3436,10248
Strayer University-Northwest Houston,7297,7297,407,378878,72883,340015,975,11366,3308,5048,1068,7268,113297,172416,169833,36087,3437,10250
Strayer University-Plano,7298,7298,408,378987,72911,340151,976,11368,3309,5049,1069,7269,113341,172482,169888,36099,3438,10252
Strayer University-Cedar Hill,7299,7299,409,379096,72939,340287,977,11370,3310,5050,1070,7270,113385,172548,169943,36111,3439,10254
Strayer University-North Dallas,7300,7300,410,379205,72967,340423,978,11372,3311,5051,1071,7271,113429,172614,169998,36123,3440,10256
Strayer University-San Antonio,7301,7301,411,379314,72995,340559,979,11374,3312,5052,1072,7272,113473,172680,170053,36135,3441,10258
Strayer University-Stafford,7302,7302,412,379423,73023,340695,980,11376,3313,5053,1073,7273,113517,172746,170108,36147,3442,10260
WestMed College - Merced,7303,7303,413,379532,73051,340831,981,11378,3314,5054,1074,7274,113561,172812,170163,36159,3443,10262
Vantage College,7304,7304,414,379641,73079,340967,982,11380,3315,5055,1075,7275,113605,172878,170218,36171,3444,10264
SAE Institute of Technology San Francisco,7305,7305,415,379750,73107,341103,983,11382,3316,5056,1076,7276,113649,172944,170273,36183,3445,10266
Rasmussen College - Overland Park,7306,7306,416,379859,73135,341239,984,11384,3317,5057,1077,7277,113693,173010,170328,36195,3446,10268
National Personal Training Institute of Cleveland,7307,7307,417,379968,73163,341375,985,11386,3318,5058,1078,7278,113737,173076,170383,36207,3447,10270
Bay Area Medical Academy - San Jose Satellite Location,7308,7308,418,380077,73191,341511,986,11388,3319,5059,1079,7279,113781,173142,170438,36219,3448,10272
Excel Learning Center-San Antonio South,7309,7309,419,380186,73219,341647,987,11390,3320,5060,1080,7280,113825,173208,170493,36231,3449,10274

In [96]:
has_row_max2 = college_n.eq(college_n.max()) \
                        .cumsum() \
                        .cumsum() \
                        .eq(1) \
                        .any(axis='columns')

In [97]:
has_row_max2.head()

INSTNM
Alabama A & M University               False
University of Alabama at Birmingham    False
Amridge University                     False
University of Alabama in Huntsville    False
Alabama State University               False
dtype: bool

In [98]:
has_row_max2.sum()

16

In [99]:
idxmax_cols = has_row_max2[has_row_max2].index
idxmax_cols

Index(['Thunderbird School of Global Management',
       'Southwest University of Visual Arts-Tucson', 'ABC Beauty College Inc',
       'Velvatex College of Beauty Culture',
       'California Institute of Technology',
       'Le Cordon Bleu College of Culinary Arts-San Francisco',
       'MTI Business College Inc', 'Dongguk University-Los Angeles',
       'Mr Leon's School of Hair Design-Moscow',
       'Haskell Indian Nations University', 'LIU Brentwood',
       'Medical College of Wisconsin', 'Palau Community College',
       'California University of Management and Sciences',
       'Cosmopolitan Beauty and Tech School', 'University of Phoenix-Arizona'],
      dtype='object', name='INSTNM')

In [100]:
set(college_n.idxmax().unique()) == set(idxmax_cols)

True

In [101]:
%timeit college_n.idxmax().values

2.24 ms ± 50.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [102]:
%timeit college_n.eq(college_n.max()) \
                        .cumsum() \
                        .cumsum() \
                        .eq(1) \
                        .any(axis='columns') \
                        [lambda x: x].index

6.68 ms ± 363 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

## Finding the most common maximum

In [103]:
college = pd.read_csv('master/data/college.csv', index_col='INSTNM')
college_ugds = college.filter(like='UGDS_')
college_ugds.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [104]:
highest_percentage_race = college_ugds.idxmax(axis='columns')
highest_percentage_race.head()

INSTNM
Alabama A & M University               UGDS_BLACK
University of Alabama at Birmingham    UGDS_WHITE
Amridge University                     UGDS_BLACK
University of Alabama in Huntsville    UGDS_WHITE
Alabama State University               UGDS_BLACK
dtype: object

In [107]:
highest_percentage_race.value_counts(normalize=True)

UGDS_WHITE    0.670352
UGDS_BLACK    0.151586
UGDS_HISP     0.129473
UGDS_UNKN     0.023422
UGDS_ASIAN    0.012074
UGDS_AIAN     0.006110
UGDS_NRA      0.004073
UGDS_NHPI     0.001746
UGDS_2MOR     0.001164
dtype: float64

In [108]:
college_black = college_ugds[highest_percentage_race == 'UGDS_BLACK']
college_black = college_black.drop('UGDS_BLACK', axis='columns')
college_black.idxmax(axis='columns').value_counts(normalize='True')

UGDS_WHITE    0.661228
UGDS_HISP     0.230326
UGDS_UNKN     0.071977
UGDS_NRA      0.018234
UGDS_ASIAN    0.009597
UGDS_2MOR     0.006718
UGDS_NHPI     0.000960
UGDS_AIAN     0.000960
dtype: float64